name: Prettier
on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        name: Prettier
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: bahmutov/npm-install@v1

            - run: npm run lint
            - run: git status
